# Generated by Django 3.0.5 on 2020-10-12 21:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderConfirmation',
            fields=[
                ('order_confirmation_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('order_confirmation', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('purchase_products', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('order_total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'order_confirmation',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('code', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('inventory_on_hand', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('product_details_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_type', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('category', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medi_ecommerce_rest_api.Products')),
            ],
            options={
                'db_table': 'product_details',
            },
        ),
        migrations.CreateModel(
            name='OrderCreate',
            fields=[
                ('order_create_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('shipping_address', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('billing_address', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('purchase_products', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medi_ecommerce_rest_api.Products')),
            ],
            options={
                'db_table': 'order_create',
            },
        ),
    ]