# Generated by Django 3.0.5 on 2020-10-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_ecommerce_rest_api', '0003_auto_20201014_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderconfirmation',
            old_name='order_confirmation_id',
            new_name='confirmation_code',
        ),
        migrations.RenameField(
            model_name='orderconfirmation',
            old_name='order_confirmation',
            new_name='customer_email',
        ),
        migrations.AddField(
            model_name='orderconfirmation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
