# Generated by Django 3.0.5 on 2020-10-15 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medi_ecommerce_rest_api', '0004_auto_20201014_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconfirmation',
            name='order_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medi_ecommerce_rest_api.OrderCreate'),
        ),
        migrations.AddField(
            model_name='ordercreate',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medi_ecommerce_rest_api.Products'),
        ),
    ]
